// Generated by LiveScript 1.2.0
(function(){
  var Live, Cell, DB, db, a, b;
  Live = require('./');
  Cell = require('./cell');
  DB = require('./db');
  db = DB();
  a = Cell('bar');
  b = Cell();
  db.add(a);
  a.bind(b, {
    mapper: function(it){
      return "foo" + it;
    },
    reverseMapper: function(it){
      return it.replace(/^foo/, '');
    }
  });
  console.log(a.get(), b.get());
  b.set('foobaz');
  console.log(a.get(), b.get());
}).call(this);
